about:
  body: |-
    对于我来讲，开发是一件有趣的事。电脑通上电，就能把一个想法变成一个实实在在的作品。<br/>
    优雅，实在是太优雅了！
  text: 做些有意义的事件
  title: 关于我
clients:
  horizontal-scrolling: ''
  list:
    - logo: assets/img/clients/envato.jpg
      title: 环境
      url: 'https://github.com/raviriley/agency-jekyll-theme'
    - logo: assets/img/clients/designmodo.jpg
      title: 设计模式
      url: 'https://github.com/raviriley/agency-jekyll-theme'
    - logo: assets/img/clients/themeforest.jpg
      title: 主题森林
      url: 'https://github.com/raviriley/agency-jekyll-theme'
    - logo: ''
      title: ''
      url: ''
  max-height: ''
contact:
  email: 电子邮箱*
  email-validation: 请输入您的电子邮件地址。
  message: 信息*
  message-validation: 请输入消息。
  name: 姓名*
  name-validation: 请输入你的名字。
  phone: 电话号码
  phone-validation: 请输入您的电话号码。
  subject: 联系表格提交
  submit: 发送消息
  text: '有想法？可以联系我哦! '
  title: 联系我
footer:
  legal: 隐私政策
  social:
    - icon: fab fa-github
      url: 'https://github.com/xuzhuoxi'
  url: legal_en
header:
  button: 告诉我更多
  buttonlink: '#service'
  text: 很高兴遇见你
  title: 欢迎
navigation:
  - board_on: 'yes'
    nav_on: 'yes'
    page: services.html
    section: service
    title: 服务
  - board_on: 'yes'
    nav_on: 'yes'
    page: portfolio.html
    section: portfolio
    title: 工具
  - board_on: 'yes'
    nav_on: 'yes'
    page: about.html
    section: about
    title: 关于
  - board_on: 'yes'
    nav_on: 'yes'
    page: timeline.html
    section: timeline
    title: 经历
  - board_on: 'no'
    nav_on: 'no'
    page: team.html
    section: team
    title: 团队
  - board_on: 'no'
    nav_on: 'no'
    page: clients.html
  - board_on: 'yes'
    nav_on: 'yes'
    page: contact.html
    section: contact
    title: 联系我们
  - board_on: 'no'
    nav_on: 'no'
    title: 源代码
    url: 'https://github.com/raviriley/agency-jekyll-theme/'
portfolio:
  closebutton: 关闭
  download: 下载
  list:
    - alt: GameDriver Pro Logo
      download: 'https://assetstore.unity.com/packages/slug/234202'
      image: assets/img/portfolio/01-GameDriver Pro-400x300.jpg
      itemid: id01
      more: 'https://www.xuzhuoxi.com/GameDriver-Docs/'
      subtitle: GameDriver Pro 是一款基于Unity引擎的游戏开发框架。
      title: GameDriver Pro
    - alt: ExcelExporter Logo
      download: 'https://github.com/xuzhuoxi/ExcelExporter/releases'
      image: assets/img/portfolio/02-ExcelExporter-400x300.jpg
      itemid: id02
      more: 'https://github.com/xuzhuoxi/ExcelExporter'
      subtitle: 根据模板导出Excel数据。支持**多种数据格式**和**任何一种编程语言**。支持**多操作系统**。
      title: ExcelExporter
    - alt: FileSync Logo
      download: 'https://github.com/xuzhuoxi/FileSync/releases'
      image: assets/img/portfolio/03-FileSync-400x300.jpg
      itemid: id03
      more: 'https://github.com/xuzhuoxi/FileSync'
      subtitle: 通过配置进行同步、复制、删除文件，是**多工作区协作**的利器。支持**多操作系统**。
      title: FileSync
    - alt: SVNArchiver Logo
      download: 'https://github.com/xuzhuoxi/SVNArchiver/releases'
      image: assets/img/portfolio/04-SVNArchiver-400x300.jpg
      itemid: id04
      more: 'https://github.com/xuzhuoxi/SVNArchiver'
      subtitle: 针对SVN进行数据归档的工具。支持**完整归档**、**差异归档**。支持**多操作系统**。
      title: SVNArchiver
    - alt: ImageResizer Logo
      download: 'https://github.com/xuzhuoxi/ImageResizer/releases'
      image: assets/img/portfolio/05-ImageResizer-400x300.jpg
      itemid: id05
      more: 'https://github.com/xuzhuoxi/ImageResizer'
      subtitle: 按比例或尺寸对图片进行大小调整，支持**配置**、**批量**处理。支持**多操作系统**。
      title: ImageResizer
    - alt: ImageSplitter Logo
      download: 'https://github.com/xuzhuoxi/ImageSplitter/releases'
      image: assets/img/portfolio/06-ImageSplitter-400x300.jpg
      itemid: id06
      more: 'https://github.com/xuzhuoxi/ImageSplitter'
      subtitle: 按固定尺寸或数量把图片进行分割。支持**大分辨率**图片。支持**规律化命名**。支持**多操作系统**。
      title: ImageSplitter
    - alt: ImageClearer Logo
      download: 'https://github.com/xuzhuoxi/ImageClearer/releases'
      image: assets/img/portfolio/07-ImageClearer-400x300.jpg
      itemid: id07
      more: 'https://github.com/xuzhuoxi/ImageClearer'
      subtitle: 清理目录中像素符合条件的图片。
      title: ImageClearer
  more: 了解更多
  text: 有效地利用工具，使您的工作变得高效起来
  title: 工具
services:
  list:
    - desc: 对客户来说，注意脂肪处理过程非常重要。 最小的，最重要的是，阻碍了从伟大的工程师那里发现这些东西的工程师。
      icon: fas fa-shopping-cart
      title: 电子商务
    - desc: 对客户来说，注意脂肪处理过程非常重要。 最小的，最重要的是，阻碍了从伟大的工程师那里发现这些东西的工程师。
      icon: fas fa-laptop
      title: 响应式设计
    - desc: 您在此处的描述，完整的 **Markdown** 支持
      icon: fab fa-markdown
      title: '[Markdown](https://en.wikipedia.org/wiki/Markdown)'
  text: Lorem ipsum
  title: 服务
team:
  people:
    - image: assets/img/team/500x500.jpg
      name: 凯·加兰
      role: 首席设计师
      social:
        - icon: fab fa-twitter
          url: 'https://twitter.com'
        - icon: fab fa-facebook-f
          url: 'https://facebook.com'
        - icon: fab fa-linkedin-in
          url: 'https://linkedin.com'
    - image: assets/img/team/2.jpg
      name: Larry Parker
      role: 首席营销官
      social:
        - icon: fab fa-twitter
          url: 'https://twitter.com'
        - icon: fab fa-facebook-f
          url: 'https://facebook.com'
        - icon: fab fa-linkedin-in
          url: 'https://linkedin.com'
    - image: assets/img/team/500x500.jpg
      name: Diana Perterson
      role: 首席开发人员
      social:
        - icon: fab fa-twitter
          url: 'https://twitter.com'
        - icon: fab fa-facebook-f
          url: 'https://facebook.com'
        - icon: fab fa-linkedin-in
          url: 'https://linkedin.com'
  subtext: >-
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque,
    laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea,
    alias ut unde. **Markdown** supported.
  text: Lorem ipsum dolor sit amet consectetur.
  title: 我们的团队
timeline:
  align: right
  events:
    - desc: 就读于**华南师范大学**，专业为**软件工程**。
      image: assets/img/timeline/0.png
      title: 我的大学生活
      year: 2006-2010
    - desc: 2010年7月大学毕业，开始了职业生涯。
      image: assets/img/timeline/1.png
      title: 毕业
      year: 2010年7月
    - alt: Aola
      desc: |-
        就职于**广州百田信息科技有限公司**。<br/>
        作为一名游戏开发工程师，服务于**奥拉星项目组**。<br/>
        是我巩固技术基础的重要一段时间。
      image: assets/img/timeline/2.jpg
      title: 游戏开发工程师
      year: 2010-2015
    - align: right
      desc: |-
        做了不少HTML游戏项目。<br/>
        以中度和重度为主。
      image: assets/img/timeline/3.png
      title: HTML5 游戏开发主程序
      year: 2015-2018
    - desc: |-
        做些有意义的事件<br/>
        摸爬滚打中……
      image: assets/img/timeline/4.jpg
      title: Unity 游戏开发主程序
      year: 2018-现在
  text: 漫漫人生，能称为青春的却只有一小段。
  title: 个人经历
title: 快乐生活
